### ISSUE TITLE
Bug in serializing encoded password (business_shortcode+ passcode+ time) in Mpesa Express stk_push

### ISSUE THREAD

**Issue by GrishonNganga** [allansifuna/Flask-Mpesa#2]
First of all. Good stuff with this library. It is very well written and documented.

So. I encountered this problem where I had passed everything as expected to use the Mpesa express stkpush. But I kept getting this error.

<img width="1110" alt="stk" src="https://user-images.githubusercontent.com/52824774/96151796-7fa1ba00-0f14-11eb-9ea2-ecdbb22453f1.PNG">

After a very long time I discovered that the encoded password was a byte and could not be serialized so as to be passed in the requested body. 

This is a screenshot of a segment of the class before I refactored it.

<img width="835" alt="stk_before" src="https://user-images.githubusercontent.com/52824774/96152462-3e5dda00-0f15-11eb-8e01-f1b6fb62a69c.PNG">

And after.

<img width="823" alt="stk_after" src="https://user-images.githubusercontent.com/52824774/96152506-4a499c00-0f15-11eb-8829-b1d52ec094c5.PNG">

Decoding the password to a string worked for me and everything else was seamless. 

I am not sure if it is an isolated case for me or for others as well, so I thought I'd raise this issue.

**Comment by allansifuna** [comment]
Thank you Mr.Gitonga for reaching out, am sure to fix the bug as soon as
possible.
